### ISSUE TITLE
defining basis functions + warning

### ISSUE THREAD

**Issue by francispoulin** [spectralDNS/shenfun#41]
I am learning shenfun and really impressed by it.  However, I do have a couple of questions.

I first wrote a Fourier based solver for advection-diffusion and works very nicely.  I've since tried to play with a Chebyshev version, since it allows for Dirichlet and Neumann boundary conditions.  I have two questions.

First, is this how you suggest we define these functions in the latest version?  I got this from old code and suspect I should update it but not sure if that is true.

`# Defining basis functions
    F0 = ShenDirichletBasis (N[0], quad = 'GC', bc=(0.,0.), domain=(0.,L[0]),
                           padding_factor=1, dealias_direct=True)
    F1 = ShenDirichletBasis (N[1], quad = 'GC', bc=(0.,0.), domain=(0.,L[1]),
                             padding_factor=1, dealias_direct=True)
`

Second, I get the following warning.

`#error

     python Advection_shenfun.py 
    /home/fpoulin/software/anaconda3/envs/shenfun/lib/python3.8/site- 
    packages/scipy/sparse/linalg/dsolve/linsolve.py:137: SparseEfficiencyWarning: spsolve requires A 
    be CSC or CSR matrix format
      warn('spsolve requires A be CSC or CSR matrix format',
`

**Comment by mikaem** [comment]
Look at the demos for how to use the newest version of the code. There are many problems there with one inhomogeneous direction coupled with periodic (Fourier). See, e.g., the [2D Poisson equation with Fourier in one direction and Dirichlet in the other](https://github.com/spectralDNS/shenfun/blob/master/demo/dirichlet_poisson3D.py).

To create an approximation space for Dirichlet do:

    B = Basis(N, 'C', bc=(0, 0))

where `C` can be switched with `L` for Legendre. I need more details for the warning.

**Comment by francispoulin** [comment]
Thanks.  I switched my notation and am now using the more recent, and easy to modify, system.

As for the warning, it is just a warning but it seems to happen when I do this set of operations.  It's in the project like that seems to bring the warning.

`# snipit of text

    F0 = Basis (N[0], 'C', bc=(0.,0.), domain=(0.,L[0]),
                padding_factor=1, dealias_direct=True)
    F1 = Basis (N[1], 'C', bc=(0.,0.), domain=(0.,L[1]),
                padding_factor=1, dealias_direct=True)
    TF = TensorProductSpace(comm, (F0, F1))
    TV = VectorTensorProductSpace(TF)

    Vr        = Array(TV)
    Pr, Pk = Array(TF), Function(TF)
    Pr[:] = np.sin(X[0])*np.sin(X[1])
    Pk  = TF.forward(Pr, Pk)
    Vr = project(grad(Pk),TV).backward(Vr)
`

**Comment by mikaem** [comment]
Yes, I've seen it. It's because [this solver](https://github.com/spectralDNS/shenfun/blob/4b0fdcebb719b686cdef49e52ce5aa4a77ff4d7c/shenfun/la.py#L357) is using the default `diags()` function of the matrices and not `diags('csr')`. I will consider changing the default behaviour.
 
Note that when you use two non-periodic (non-Fourier) bases, like two dirichlet Chebyshev bases, the assembled coefficient matrices that need to be solved will be tensor product matrices (i.e., the outer product of two matrices).  See [here](https://shenfun.readthedocs.io/en/latest/gettingstarted.html#multidimensional-problems) for more details.

**Comment by francispoulin** [comment]
Thank you for both pieces of information.

It's only a warning but is there a way to easily change the solver to diags('csr')?  I see there are two lines in the code but not sure if that option is accessible.

Thanks for pointing out about the two non-periodic bases.  It is certainly very slow and now I know why.  I will plaly around with that and actually wanted to try and matchin the two so now's my chance.

**Comment by mikaem** [comment]
There's currently no way to change that behaviour without hardcoding it. Please note that the solver  `SolverGeneric2NP ` is a convenient and generic solver. However, it is creating one big matrix using the `kron` product, and is generally not intended for speed. Unfortunately, a fast generic solver is hard to come by. Some very fast direct solvers are described in these two papers by [Shen](https://shenfun.readthedocs.io/en/latest/zrefs.html). However, they are quite difficult to implement, and not generic. I have implemented one of them, for Legendre bases and the Helmholtz equation, [here](https://github.com/spectralDNS/shenfun/blob/4b0fdcebb719b686cdef49e52ce5aa4a77ff4d7c/shenfun/legendre/la.py#L432). There is a similar solver for Chebyshev, but I have not implemented it yet. 

Otherwise, please note that Helmholtz and biharmonic equations are already extremely efficient in Shenfun as long as you only use one non-periodic direction, because I have implemented the direct solvers described in Shen's papers.  See the demos for use.

**Comment by francispoulin** [comment]
Thanks for the explaination.  I will read through the two papers and code you shared with me.  For the moment I can do a lot with 3D Navier Stokes and one non-periodic direction but I would like to build to having two non-periodic directions, but this is a longer term plan.  Maybe I will read the papers and give the Chebyshev solvers a go sometime, after I understand it.

Also, I noticed that the link to arxiv in the references both seem to be dead.  This link here will give you the two PDF's, any case anyone is interested.

https://scholar.google.ca/scholar?hl=en&as_sdt=0%2C5&q=Jie+Shen.+Efficient+spectral-galerkin+method+i.+direct+solvers+of+second-+and+fourth-order+equations+using+legendre+polynomials.+SIAM+Journal+on+Scientific+Computing%2C&btnG=
